apiVersion: v1
kind: Service
metadata:
  name: jaeger-svc
spec:
  selector:
    app: jaeger
  ports:
    - name: agent-compact
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: agent-binary
      protocol: TCP
      port: 6832
      targetPort: 6832
    - name: query-config
      protocol: TCP
      port: 5778
      targetPort: 5778
    - name: query-http
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: jaeger-collector-http
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: jaeger-collector-grpc
      protocol: TCP
      port: 14250
      targetPort: 14250
    - name: zipkin-collector
      protocol: TCP
      port: 9411
      targetPort: 9411
    - name: hello
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.18
        ports:
        - containerPort: 5775
          protocol: TCP
        - containerPort: 6831
          protocol: TCP
        - containerPort: 6832
          protocol: TCP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 14268
          protocol: TCP  
        - containerPort: 14250
          protocol: TCP  
        - containerPort: 9411
          protocol: TCP
      - name: hello
        image: viejo/tracing-webinar:hello
        ports:
        - containerPort: 8080
      - name: formatter
        image: viejo/tracing-webinar:formatter
        ports:
        - containerPort: 8081
      - name: publisher
        image: viejo/tracing-webinar:publisher
        ports:
        - containerPort: 8082