apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: Value defined by Kustomize ❤️
        name: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/
        ports:
        - containerPort: 80
          name: http
      volumes:
        - name: config-volume
          configMap:
            name: landing-page
            items:
            - key: landing.html
              path: index.html
