apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: deploy-nginx
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80 