apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: prod
 
patchesStrategicMerge:
- deploy-nginx.yaml
- hpa-nginx.yaml

commonAnnotations:
  env: prod

configMapGenerator:
- name: landing-page
  files:
    - landing.html
    
resources:
- ns.yaml
- ../../base
